### ISSUE TITLE
Error Traceback

### ISSUE THREAD

**Issue by godylockz** [skelsec/asyauth#7]
Error Traceback

```text
RDP         172.16.0.33     3389   WS02             [-] WS02\test:test (encoded_data must be a byte string, not NoneType)
Traceback (most recent call last):
  File "/home/kali/.local/pipx/venvs/netexec/lib/python3.12/site-packages/nxc/protocols/rdp.py", line 303, in plaintext_login
    asyncio.run(self.connect_rdp())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kali/.local/pipx/venvs/netexec/lib/python3.12/site-packages/nxc/protocols/rdp.py", line 193, in connect_rdp
    raise err
  File "/home/kali/.local/pipx/venvs/netexec/lib/python3.12/site-packages/aardwolf/connection.py", line 287, in connect
    raise err
  File "/home/kali/.local/pipx/venvs/netexec/lib/python3.12/site-packages/aardwolf/connection.py", line 390, in credssp_auth
    raise err
  File "/home/kali/.local/pipx/venvs/netexec/lib/python3.12/site-packages/asyauth/protocols/credssp/client/native.py", line 247, in authenticate
    raise Exception('CredSSP - Server sent an error! Code: %s' % hex(tdata['errorCode'] & (2**32-1)))
```

**Comment by skelsec** [comment]
Hello! Thank you for the issue report.  
Problem is that I can't trace this back to anything, because the actual exception is not visible due to the script calling aardwolf doesn't display it. Can you please provide the actual exception (should start with `CredSSP - Server sent an error!...`)
